Traceback (most recent call last):
  File "C:\Users\echaconn\Downloads\T1552_01.py", line 54, in <module>
    main()
  File "C:\Users\echaconn\Downloads\T1552_01.py", line 44, in main
    connection, session, tree = connect_to_smb(server, share, username, password)
  File "C:\Users\echaconn\Downloads\T1552_01.py", line 15, in connect_to_smb
    tree.connect()
  File "C:\Users\echaconn\AppData\Roaming\Python\Python310\site-packages\smbprotocol\tree.py", line 248, in connect
    response = self.session.connection.receive(request)
  File "C:\Users\echaconn\AppData\Roaming\Python\Python310\site-packages\smbprotocol\connection.py", line 1100, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.InvalidParameter: Received unexpected status from the server: An invalid parameter was passed to a service or function. (3221225485) STATUS_INVALID_PARAMETER: 0xc000000d

